# Problem 2:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By considering the terms in the
# Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci(val, prev, sum, max):
    if val % 2 == 0:
        sum += val
    if val + prev > max:
        return sum
    else:
        return fibonacci(val=val+prev, prev=val, sum=sum, max=max)

def solution(max):
    sum = fibonacci(val=1, prev=0, sum=0, max=max)
    return sum


def main():
    sol = solution(4000000)
    print(sol)


if __name__ == '__main__':
    main()